baseurl = "http://localhost:1313"
DefaultContentLanguage = "en"
title = "Jesse Sadler"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "A blog about early modern history and digital humanities"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Jesse Sadler"
  email = "jsadler@ucla.edu"
  twitter = "vivalosburros"
  github = "jessesadler"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Courses"
    url = "/course/"
    weight = 3

[[menu.main]]
    name = "CV"
    url = "page/cv/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 5

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 6

